# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('days', models.ManyToManyField(related_name='expenses', to='backend.Day')),
            ],
        ),
    ]
